name: eshop-local

services:
  postgres:
    image: postgres:16
    container_name: eshop-postgres
    environment:
      POSTGRES_USER: eshop
      POSTGRES_PASSWORD: eshop_pwd
      POSTGRES_DB: orderingdb
    ports:
      - "5432:5432"
    volumes:
      - eshop_pgdata:/var/lib/postgresql/data

  mongo:
    image: mongo:7
    container_name: eshop-mongo
    ports:
      - "27017:27017"
    volumes:
      - eshop_mongodata:/data/db

  redis:
    image: redis:7
    container_name: eshop-redis
    ports:
      - "6379:6379"

  kafka:
    image: bitnami/kafka:3.7
    container_name: eshop-kafka
    ports:
      - "9092:9092"
    environment:
      # KRaft mode (no Zookeeper)
      KAFKA_ENABLE_KRAFT: "yes"
      KAFKA_CFG_PROCESS_ROLES: "broker,controller"
      KAFKA_CFG_NODE_ID: "1"
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
      KAFKA_CFG_LISTENERS: "PLAINTEXT://:9092,CONTROLLER://:9093"
      KAFKA_CFG_ADVERTISED_LISTENERS: "PLAINTEXT://localhost:9092"
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT"
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: "true"
      ALLOW_PLAINTEXT_LISTENER: "yes"
    volumes:
      - eshop_kafkadata:/bitnami/kafka

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: eshop-kafka-ui
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    depends_on:
      - kafka

volumes:
  eshop_pgdata:
  eshop_mongodata:
  eshop_kafkadata:
